# This is a basic workflow to help you get started with Actions

name: autoQuestPush

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '0 1 * * *'
    
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          git config --global user.email "353783986@qq.com"
          git config --global user.name "callofblood"
          pip install requests
          pip install bs4
          pip install lxml
          python regular.py
          git config --global user.email 353783986@qq.com
          git config --global user.name callofblood
          git add .
          git commit -m "update" -a --allow-empty
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
